version: '3'

services:
  aptly:
    container_name: aptly
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

    ports:
      - 80:80

    # Create aptly-data volume,
    # otherwise use directory, fe:
    # - ./aptly-data:/opt/aptly
    volumes:
      - aptly-data:/opt/aptly

    # If want to use additional environments,
    # you can set them in .env file

volumes:
  aptly-data:
    external: true
